# Generated by Django 4.0.7 on 2025-06-25 23:20

import astek_technical_task.scheduler.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('input_schema', models.JSONField(help_text='Define expected inputs and their types, e.g. {"param1": "str", "param2": "int"}', validators=[astek_technical_task.scheduler.validators.validate_input_schema])),
                ('running_function', models.CharField(help_text="Full Python path to the function to run, e.g., 'my_app.tasks.my_task_function'", max_length=255, validators=[astek_technical_task.scheduler.validators.validate_running_function])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Predefined Task',
                'verbose_name_plural': 'Predefined Tasks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPeriodicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('periodic_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask', verbose_name='Periodic Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Periodic Task',
                'verbose_name_plural': 'User Periodic Tasks',
                'unique_together': {('user', 'periodic_task')},
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10, verbose_name='Status')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Executed at')),
                ('predefined_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='scheduler.predefinedtask', verbose_name='Predefined Task')),
                ('user_periodic_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='scheduler.userperiodictask', verbose_name='User Periodic Task')),
            ],
            options={
                'verbose_name': 'Task Execution Log',
                'verbose_name_plural': 'Task Execution Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
